version: "3.7"
services:
  # add nodejs
  nodejs:
    build: .
    container_name: nodejs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=secret
      - SESSION_SECRET=sessionsecret
    command: npm run start
